# -*- coding: utf-8 -*-
"""نظام ادراه طلاب

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sux7hhHryDiNAGq9nuYVFeeueOvsDzA8
"""

def main_list():
    print("=====قائمه رئسيه=====")
    main_list1=["إضافه طالب","عرض جميع الطلاب","البحث عن طالب","حذف الطالب","خروج", "اختر العمليه"]
    for i in(main_list1):
       print(i)
main_list()
def new_studeunt():
  choose=input("your choose prosses:")
  if choose=="1":
     print("==================\nإصافه طالب جديد =====")
     number_studeunt=input("enter your number studeunt:")
     studeunt_name=input("enter your name studeunt:")
     departament=input("enter your name department:")
     print("تمت الاضافه بالنجاح \n")
new_studeunt()
def show_studeunts():
  choose=input("your choose prosses:")
  if choose=="2":
    print("==================\n  عرض جميع الطالب==========")
    studeunt_name=["Ahmed","sara","yessina"]
    for i in (studeunt_name):
      print(i)
show_studeunts()
def search_studeunt():
  choose=input("your choose prosses")
  if choose =="3":


       print("==================\n البحث عن طالب========")
       studeunt_name=input("enter your name:")
       number_studeunt=input("enter your number:")
       print("تم البحث بالنجاح \n")

       return "اضغط enter  للعوده"




search_studeunt()
def deleted_studeunt():
    choose=input("your choose prosses")
    if choose =="4":


      print("=========حذف طالب===========")
      studeunt_name=input("enter your name:")
      print( "تم الخذف بنجاح")
    else:
      print(" لم يتم العثور علي هذا الاسم")


      return "اضغط enter  للعوده"


deleted_studeunt()
def  Exit_the_app():
    print("========خروج\n=======")
    print("شكرا لاستخدامك النظام مع السلامه!")
Exit_the_app()



"""# New Section"""